name: Release Component Version

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Get version tag
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Create Release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: Version ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false

  component:
    name: Deploy Serverless Component
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install deploy dependencies
      run: npm install
    - name: Install component dependencies
      run: cd ./src && npm install --production
    - name: Publish Serverless Component
      run: npm run publish
      env:
        SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
